### ISSUE TITLE
Правки до ДЗ 21

### ISSUE THREAD

**Issue by Dexter19** [Lilia29071978/Lilia-Krasnobai#3]
10.Додати 'Catwoman' на початок масиву names, використовуючи оператор ...
Використаємо спред оператор(або оператор 3 крапки ) для виконання цієї задачі:
names = ['Batman', 'Joker', 'Bane'];
names = [
  'Catwoman',
  ...names
];
--------------------------------------------------------------------

**Comment by Lilia29071978** [comment]
Виправила)
