### ISSUE TITLE
Правки до ДЗ 26

### ISSUE THREAD

**Issue by Dexter19** [Lilia29071978/Lilia-Krasnobai#4]
5.Створити конструктор прототипу масиву upperCase(), що перетворює символи рядка у символи верхнього регістру.

У вашому коді відбувається виклик методу upperCase(), який не існує для масивів в JavaScript. Під час виконання коду буде виникати помилка.
Ось як треба правильно запис ати у вашому конкретно варіанті:
function myFunc() {
    let arr = ['Algorithm', 'Data Structure', 'Operating System', 'html'];
    arr = arr.map(function(item) {
        return item.toUpperCase();
    });
    console.log(arr);
}

myFunc();
-----------------------------------

**Comment by Lilia29071978** [comment]
Виправила
